Agenda 20210121
sardana-org/sardana-followup pull request #72
Opened 2021-01-15 15:38 UTC by teresanunez

2021-01-18 12:50 UTC, cpascual commented
sorry if I missed it (I read it quickly) but if it has not been discussed elsewhere, maybe the migration to gitlab should be discussed...

2021-01-18 13:30 UTC, teresanunez commented
Thanks, Carlos, I have added that point.

2021-01-18 14:24 UTC, reszelaz approved these changes

2021-01-18 14:28 UTC, reszelaz requested changes
@teresanunez last time we agreed to make the meeting on 20.01.2021 Wednesday at 11:00. I don't mind moving to Thursday if all agree (then we could stay on whole Tango webinar planned for Wednesday at 10:00)

2021-01-18 14:30 UTC, teresanunez commented
Hi Zibi, it is written at 2021/01/20 also Wednesday. Where have I put it wrong?

2021-01-18 14:30 UTC, teresanunez commented
Ah!, in the title. But the agenda is right. Sorry for the confusion

2021-01-18 14:39 UTC, reszelaz approved these changes

2021-01-18 14:54 UTC, cpt-majkel approved these changes

2021-01-19 08:57 UTC, reszelaz approved these changes
Hi @teresanunez,
I just realized that we need to start discussing the Jan21 release. I suggest to add it to the agenda. Also, I corrected the order of points.

2021-01-19 08:57 UTC, reszelaz commented on 20210120/AGENDA.md
> +3. Review pending points from the previous meeting
```suggestion
4. Review pending points from the previous meeting
```

2021-01-19 08:57 UTC, reszelaz commented on 20210120/AGENDA.md
> +4. Overview of current developments / PR distribution
```suggestion
5. Overview of current developments / PR distribution
```

2021-01-19 08:57 UTC, reszelaz commented on 20210120/AGENDA.md
> +5. Migration to gitlab
```suggestion
6. Migration to gitlab
```

2021-01-19 08:57 UTC, reszelaz commented on 20210120/AGENDA.md
> +6. AOB
```suggestion
6. Sardana release Jan21
   - Who are the release managers?
   - Preselect milestone scope
7. AOB
```

2021-01-19 21:25 UTC, reszelaz commented
Hi Teresa,
I just realized the agenda for tomorrow misses all the new TODOs from the last meeting. You can easliy find them in the [20201216/MINUTES.md](https://github.com/sardana-org/sardana-followup/blob/master/20201216/MINUTES.md) - these are the "check boxes" that are not in point 6.

2021-01-19 22:37 UTC, teresanunez commented
Hi Zibi, thanks, I will try to put it before the meeting ... if not during.

2021-01-20 08:02 UTC, aureocarneiro approved these changes

2021-01-20 09:11 UTC, merged