Add agenda for community followup meeting 20210923
sardana-org/sardana-followup pull request #83
Opened 2021-09-21 07:50 UTC by johanfforsberg

Kept most items from last meeting (20210610) but removed a few things
that were either specific to that meeting or where the linked issue/PR
was closed.

2021-09-21 09:02 UTC, teresanunez commented
Hi Johan, Zibi wanted me to start the meeting reporting shortly about the sardana configuration tool used
at DESY. Could you add that?. Many thanks.

2021-09-21 09:02 UTC, teresanunez approved these changes

2021-09-22 09:54 UTC, reszelaz requested changes
Hi @johanfforsberg,
I see that you based the agenda proposal on the 2021-06-10 agenda, not considering the minutes. I'm talking mainly about the point "Overview of current developments / PR distribution". I suggest removing points that we agreed on the last time unless you want to reopen the discussion.

Also, as @teresanunez mentioned, please insert a new starting point: Sardana Configuration Tool. Teresa will give us a short overview of the tool they developed at DESY.

2021-09-22 09:54 UTC, reszelaz commented on 20210923/AGENDA.md
> +	      - Johan wanted to have a look to the PR
```suggestion
```
This point was checked in the 20210610 minutes. I would remove it from the agenda.

2021-09-22 09:54 UTC, reszelaz commented on 20210923/AGENDA.md
> +        - [ ] Before starting the scan, Sardana should verify the states of measurement channels.
```suggestion
```
This point was checked in the 20210610 minutes. I would remove it from the agenda.

2021-09-22 09:54 UTC, reszelaz commented on 20210923/AGENDA.md
> +      - Bug or feature?
```suggestion
```
I would remove this point. In 20210610 minutes we said: 
>  It will be discussed in the issue. Point to be removed.

2021-09-22 09:54 UTC, reszelaz commented on 20210923/AGENDA.md
> +      - Design proposed. Any volunteers to work on that?
```suggestion
```
I would remove this point. In 20210610 minutes we said:
> Design proposed. Any volunteers to work on that? Point to be removed. Somebody should look at what is proposed.

2021-09-22 09:54 UTC, reszelaz commented on 20210923/AGENDA.md
> +      - Anyone knows on recorders usign this information?
```suggestion
```
I would remove this point. In 20210610 minutes we said:
> Anyone knows on recorders using this information? No update. To be removed and discussed in the issue.

2021-09-22 09:54 UTC, reszelaz commented on 20210923/AGENDA.md
> +    - Refractor hooks for move macros [#1544](https://github.com/sardana-org/sardana/pull/1544)
```suggestion
    - Refractor hooks for move macros [#1544](https://github.com/sardana-org/sardana/pull/1544)
```
I would remove this point. In 20210610 minutes we said:
> Still to be reviewed. To be removed.

2021-09-22 09:54 UTC, reszelaz commented on 20210923/AGENDA.md
> +    - Last scan macro data http://github.com/sardana-org/sardana/issues/290#issuecomment-819440784
```suggestion
```
I would remove this point. In 20210610 minutes we said:
> To be removed.

2021-09-22 09:54 UTC, reszelaz commented on 20210923/AGENDA.md
> +    - Not possible to call mAPI methods (macro API) after stopping/aborting a macro (SF#9) [#10](https://github.com/sardana-org/sardana/issues/10)
```suggestion
```
I would remove this point. In 20210610 minutes we said:
> To be removed.

2021-09-22 09:54 UTC, reszelaz requested changes
Hi @johanfforsberg,
I see that you based the agenda proposal on the 2021-06-10 agenda, not considering the minutes. I'm talking mainly about the point "Overview of current developments / PR distribution". I suggest removing points that we agreed on the last time unless you want to reopen the discussion.

Also, as @teresanunez mentioned, please insert a new starting point: Sardana Configuration Tool. Teresa will give us a short overview of the tool they developed at DESY.

2021-09-22 13:20 UTC, johanfforsberg commented
Sorry Zibi, this was a bit too hurried by me. Thanks for the feedback, I hope I have addressed it all!

2021-09-23 10:22 UTC, reszelaz approved these changes

2021-09-23 10:23 UTC, reszelaz approved these changes
> Sorry Zibi, this was a bit too hurried by me. Thanks for the feedback, I hope I have addressed it all!

No worries! Thanks for the meeting preparation works!

I just added a point on the Sardana 3.2 release. I will proceed to merge.

2021-09-23 10:23 UTC, merged